# travis config, based on https://github.com/craigcitro/r-travis

language: c

sudo: true

env:
   global:
     - _R_CHECK_TIMINGS_=0

branches:
  only:
   - master
   - repofix

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh github_package jimhester/covr
  - ./travis-tool.sh github_package hadley/testthat
  - ./travis-tool.sh github_package berndbischl/BBmisc
  - ./travis-tool.sh install_deps

script: ./travis-tool.sh run_tests

after_success:
  - Rscript -e 'library(covr);coveralls()'

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    recipients:
        - kerschke@uni-muenster.de
    on_success: change
    on_failure: always
